### PR TITLE
CI builds through github actions using JFPatch-as-a-service

### PR DESCRIPTION
**Pull request by gerph**
Needed a few changes to make it work, but it's functional.

The conversion to BasicText format
isn't required, but as it's easier to edit and diff, I made that change
(I don't have a RISC OS editor for tokenised BASIC files).

Once that was done, I updated the !!Release script to run the text
versions, and fixed the killing of ShellCLI (it's not in the environment),
and then added a .robuild.yml file which will now be used by the
JFPatchAsAService system when it receives a file.

https://jfpatch.riscos.online/robuildyaml.html now documents the
configuration file (and uses the LineEditor build as an example).

The environment variable Sys$Environment that I set is utterly
unnecessary, but I was testing out that the environment variables worked,
so that they could be used to differentiate automated and non-automated
builds.

If I zip up the sources and send them to the service, I get back a zip
archive containing the release.

The github workflows files have been created to show that it can build the
job on each push, using JFPatch as a service. And it has a                          
little tick by it to show that the action worked! If you go to the action,                      
you can see that the job completed, and the messages if you want. And even                      
download the artifact... which Github helpfully has put inside a zip                            
archive - so it's a zip inside a Zip. Since they wouldn't know to create                        
RISC OS attributes in their Zip, that's probably fine. It'd be nice if                          
they could just pass the zip through directly.                                                  
                                                                                                
https://github.com/actions/upload-artifact/issues/3 - describes the issue.

### CODE REVIEW

**Comment by gerph** [comment]
I don't see an action having started for this job, so I guess either pull requests don't get a trigger, or it's disabled on this repo. I'm not sure, 'cos it worked on mine.

**Comment by philpem** [comment]
Nice one, @gerph! I suspect the triggers will kick in once it merges... we'll soon find out.

Thanks for your hard work. You're making me wish JFPatch As A Service could support the ROOL C environment - it'd be great for building ClearView.

**Comment by philpem** [comment]
Okay now it has run (https://github.com/philpem/LineEditor/actions/runs/113509629) my only remaining comment is that the build output seems to be a ZIP file which contains another ZIP file...

**Comment by gerph** [comment]
> Nice one, @gerph! I suspect the triggers will kick in once it merges... we'll soon find out.
> 
> Thanks for your hard work. You're making me wish JFPatch As A Service could support the ROOL C environment - it'd be great for building ClearView.

It could.                                                                                       
                                                                                                
It currently has builds of the standard tools - such source that I have
building things. I can build simple tools like my pascal compiler without
much issue.

It's not the CI environment that I use myself - I build most of the components cross-compiled, rather than running the compiler in RISC OS itself - so it's not an area I've put much work into. I might have a look at ClearView and see what support it needs. I almost certainly have the libraries already built anyhow.

**Comment by gerph** [comment]
> Okay now it has run (https://github.com/philpem/LineEditor/actions/runs/113509629) my only remaining comment is that the build output seems to be a ZIP file which contains another ZIP file...

Yeah, it's annoying - that's the thing about the upload-artifacts. What happens is that the workflow supplies a zip archive as the artifact, and then when you come to download the artifacts, it puts them in a zip.

I can't just give it the files, having extracted them, because that would lose the RISC OS filetypes. Unless you were willing to put up with the NFS encoding of filenames, which... I suspect most people wouldn't like.

**Comment by philpem** [comment]
> > Thanks for your hard work. You're making me wish JFPatch As A Service could support the ROOL C environment - it'd be great for building ClearView.
> 
> It could.
> 
> It currently has builds of the standard tools - such source that I have
> building things. I can build simple tools like my pascal compiler without
> much issue.

I think the issue would be one of copyright, making it available as an online tool when it's sold for £50.
I'll likely just set up my own CI pipeline using Jenkins, RPCEmu and HostFS.


> Yeah, it's annoying - that's the thing about the upload-artifacts. What happens is that the workflow supplies a zip archive as the artifact, and then when you come to download the artifacts, it puts them in a zip.
> 
> I can't just give it the files, having extracted them, because that would lose the RISC OS filetypes. Unless you were willing to put up with the NFS encoding of filenames, which... I suspect most people wouldn't like.

True enough. I'm just about to merge another branch to get rid of the tokenised BASIC files from the repo as it seems they're no longer needed now we're using text files. That should be much easier for change tracking in the future.

**Pull request merged**
